CREATE TABLE Products (
	Id INT NOT NULL,
	Name NVARCHAR(100) NULL,
	Description NVARCHAR(200) NULL,
	CreatedDate DATETIME2 NOT NULL CONSTRAINT [DF_Products_CreatedDate] DEFAULT GETUTCDATE(),
	CreatedBy NVARCHAR(150) NOT NULL,
	CONSTRAINT PK_Product PRIMARY KEY(Id)
 );