CREATE TABLE Persons (
	Id INT NOT NULL,
	Name NVARCHAR(100) NULL,
	LastName NVARCHAR(255) NULL,
	CreatedDate DATETIME2 NOT NULL CONSTRAINT [DF_Persons_CreatedDate] DEFAULT GETUTCDATE(),
	ModifiedDate DATETIME2 NULL
	CONSTRAINT PK_Persons PRIMARY KEY(Id)
 );